spring:
  application:
    # 应用名称
    name: driftbottle-service-gateway
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用 Sentinel 作为熔断器

    # 路由网关配置
    # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
    gateway:
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        - id: driftbottle-service-consumer-account
          uri: lb://driftbottle-service-consumer-account
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=1

server:
  port: 9999


# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug