spring:
  application:
    name: driftbottle-service-consumer-account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

feign:
  sentinel:
    enabled: true

server:
  port: 9500

management:
  endpoints:
    web:
      exposure:
        include: "*"